import * as fs from 'fs';
import * as path from 'path';
import { aiLogger, callClaude, extractText, isAiEnabled } from './anthropic-client';
import { loadPrompt } from './prompt-loader';

export type TestKind = 'ui' | 'api';

const OUT_DIR = path.join('tests', '_generated');

// Header line — prevents accidental commits of unreviewed AI output.
// Also makes draft files trivial to grep / lint out.
const HEADER = `// [AI-DRAFT] generated by scripts/generate-test.ts — review before committing\n`;

function listFiles(dir: string, ext: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(p, ext));
    else if (entry.name.endsWith(ext)) out.push(p);
  }
  return out;
}

function readSafe(p: string, maxChars = 3000): string {
  if (!fs.existsSync(p)) return '';
  return fs.readFileSync(p, 'utf8').slice(0, maxChars);
}

function collectProjectContext(kind: TestKind): string {
  const poms = listFiles('src/pages', '.ts');
  const clients = listFiles('src/api/clients', '.ts');
  const exampleSpec =
    kind === 'api'
      ? readSafe('tests/regression/api/booking-crud.spec.ts')
      : readSafe('tests/regression/ui/booking-flow.spec.ts');

  return [
    `Available Page Objects:\n${poms.map((p) => '  - ' + p).join('\n')}`,
    '',
    `Available API clients:\n${clients.map((p) => '  - ' + p).join('\n')}`,
    '',
    `Example spec (style reference):`,
    '```ts',
    exampleSpec,
    '```',
  ].join('\n');
}

export async function generateTest(requirement: string, kind: TestKind): Promise<string> {
  if (!isAiEnabled()) {
    throw new Error('ANTHROPIC_API_KEY is not set — cannot generate.');
  }
  aiLogger.info({ requirement, kind }, 'generating draft spec');

  const prompt = loadPrompt('test-generator');
  const resp = await callClaude(
    {
      max_tokens: 2048,
      messages: [
        {
          role: 'user',
          content: prompt.render({
            requirement,
            kind,
            projectContext: collectProjectContext(kind),
          }),
        },
      ],
    },
    {
      meta: {
        module: 'test-generator',
        promptName: prompt.meta.name,
        promptVersion: prompt.meta.version,
      },
    },
  );

  const body = extractText(resp.content);
  // Strip any stray markdown fences just in case
  const cleaned = body
    .replace(/^```(?:ts|typescript)?\s*\n?/i, '')
    .replace(/\n?```\s*$/i, '')
    .trim();

  return HEADER + cleaned + '\n';
}

export function writeGenerated(code: string, slug: string): string {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const fileName = path.join(OUT_DIR, `${slug}.spec.ts`);
  fs.writeFileSync(fileName, code, 'utf8');
  return fileName;
}

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50);
}
