import * as fs from 'fs';
import * as path from 'path';
import { aiLogger } from './anthropic-client';
import { getProvider } from './providers';
import { loadPrompt } from './prompt-loader';
import { detectInjection, sanitizeUntrusted } from './redaction';
import { rankBm25 } from './retrieval/bm25';

export type TestKind = 'ui' | 'api';

const OUT_DIR = path.join('tests', '_generated');

// Header line — prevents accidental commits of unreviewed AI output.
// Also makes draft files trivial to grep / lint out.
const HEADER = `// [AI-DRAFT] generated by scripts/generate-test.ts — review before committing\n`;

function listFiles(dir: string, ext: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(p, ext));
    else if (entry.name.endsWith(ext)) out.push(p);
  }
  return out;
}

function readSafe(p: string, maxChars = 3000): string {
  if (!fs.existsSync(p)) return '';
  return fs.readFileSync(p, 'utf8').slice(0, maxChars);
}

interface SpecDoc {
  id: string;
  text: string;
}

// Candidate corpus for retrieval, scoped to the kind of test we're drafting.
function specCorpus(kind: TestKind): SpecDoc[] {
  const roots =
    kind === 'api'
      ? ['tests/regression/api', 'tests/api/contracts', 'tests/negative/api', 'tests/smoke/api']
      : ['tests/regression/ui', 'tests/negative/ui', 'tests/smoke', 'tests/visual'];
  return roots
    .flatMap((r) => listFiles(r, '.spec.ts'))
    .map((id) => ({ id, text: readSafe(id, 3000) }));
}

function fallbackExample(kind: TestKind): SpecDoc {
  const id =
    kind === 'api'
      ? 'tests/regression/api/booking-crud.spec.ts'
      : 'tests/regression/ui/booking-flow.spec.ts';
  return { id, text: readSafe(id, 3000) };
}

// Lightweight RAG: ground generation in the existing specs most relevant to the
// requirement (BM25 over the spec corpus), not one fixed example. Falls back to a
// known example when nothing scores (e.g. a brand-new area or an empty corpus).
function retrieveExamples(kind: TestKind, requirement: string): SpecDoc[] {
  const ranked = rankBm25(requirement, specCorpus(kind), 2);
  return ranked.length > 0 ? ranked.map((r) => r.doc) : [fallbackExample(kind)];
}

function collectProjectContext(kind: TestKind, requirement: string): string {
  const poms = listFiles('src/pages', '.ts');
  const clients = listFiles('src/api/clients', '.ts');
  const examples = retrieveExamples(kind, requirement)
    .map((d) => ['// ' + d.id, '```ts', d.text, '```'].join('\n'))
    .join('\n\n');

  return [
    `Available Page Objects:\n${poms.map((p) => '  - ' + p).join('\n')}`,
    '',
    `Available API clients:\n${clients.map((p) => '  - ' + p).join('\n')}`,
    '',
    `Most relevant existing specs (retrieved by similarity — style + pattern reference):`,
    examples,
  ].join('\n');
}

export async function generateTest(requirement: string, kind: TestKind): Promise<string> {
  const provider = getProvider();
  if (!provider.isConfigured()) {
    throw new Error(`AI provider "${provider.name}" is not configured — cannot generate.`);
  }
  aiLogger.info({ requirement, kind, provider: provider.name }, 'generating draft spec');

  // The requirement is free-text from a user/CLI — untrusted. Flag injection for
  // the trace; the v2 prompt fences it as data and sanitize blocks fence breakout.
  const scan = detectInjection(requirement);
  if (scan.suspected) {
    aiLogger.warn(
      { patterns: scan.patterns },
      'possible prompt-injection in requirement — fenced as data',
    );
  }

  const prompt = loadPrompt('test-generator');
  const resp = await provider.complete({
    maxTokens: 2048,
    messages: [
      {
        role: 'user',
        text: prompt.render({
          requirement: sanitizeUntrusted(requirement),
          kind,
          projectContext: collectProjectContext(kind, requirement),
        }),
      },
    ],
    meta: {
      module: 'test-generator',
      promptName: prompt.meta.name,
      promptVersion: prompt.meta.version,
      injectionSuspected: scan.suspected,
    },
  });

  const body = resp.text;
  // Strip any stray markdown fences just in case
  const cleaned = body
    .replace(/^```(?:ts|typescript)?\s*\n?/i, '')
    .replace(/\n?```\s*$/i, '')
    .trim();

  return HEADER + cleaned + '\n';
}

export function writeGenerated(code: string, slug: string): string {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const fileName = path.join(OUT_DIR, `${slug}.spec.ts`);
  fs.writeFileSync(fileName, code, 'utf8');
  return fileName;
}

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50);
}
